openapi: 3.0.3
info:
  version: 0.0.1
  title: Elevato to Elivion API
servers:
  - url: https://{customerDomain}.elevato.net/services
paths:
  /v1/Elivion/CVAssistantResultIncomplete:
    $ref: './paths/elivion.yaml#/analysis-error'
  /v1/Elivion/CVAssistantResultComplete:
    $ref: './paths/elivion.yaml#/analysis-results'


