openapi: 3.0.3
info:
  version: 0.0.1
  title: Elevato to Elivion API
servers:
  - url: https://{customerDomain}.elevato.net/services
paths:
  /v1/Elivion/CVAssistantResultIncomplete:
    $ref: './paths/elevato.yaml#/analysis-error'
  /v1/Elivion/CVAssistantResultComplete:
    $ref: './paths/elevato.yaml#/analysis-results'

components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-KEY


