openapi: 3.0.3
info:
  version: 0.0.1
  title: Elevato to Elivion API
servers:
  - url: https://cv-assistant.elivion.io
paths:
# Customers
  /api/elevato/v1/customers:
    $ref: './paths/customers.yaml#/create-customer'
  /api/elevato/v1/customers/{customerId}:
    $ref: './paths/customers.yaml#/update-customer'

# Recruitments
  /api/elevato/v1/customers/{customerId}/recruitment:
    $ref: './paths/recruitment.yaml#/create-process'
  /api/elevato/v1/customers/{customerId}/recruitment/{externalRecruitmentProjectId}:
    $ref: './paths/recruitment.yaml#/update-process'

# Candidates
  /api/elevato/v1/customers/{customerId}/recruitment/{externalRecruitmentProjectId}/candidates:
    $ref: './paths/recruitment.yaml#/create-candidate'
  /api/elevato/v1/customers/{customerId}/recruitment/{externalRecruitmentProjectId}/candidates/{externalCandidateId}/file:
    $ref: './paths/recruitment.yaml#/upload-candidate-file'
  /api/elevato/v1/customers/{customerId}/recruitment/{externalRecruitmentProjectId}/candidates/{externalCandidateId}:
    $ref: './paths/recruitment.yaml#/delete-candidate'

components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-KEY
    customerApiKey:
      type: apiKey
      in: header
      name: X-CUSTOMER-API-KEY


